# Generated by Django 5.0.4 on 2024-05-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
