# Generated by Django 5.0.4 on 2024-05-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_direccion_colonia'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='estado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='colonia',
            field=models.CharField(blank=True, default='cd', max_length=100),
            preserve_default=False,
        ),
    ]
