# Generated by Django 5.0.4 on 2024-05-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_direccion_estado_alter_cliente_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='colonia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='estado',
            field=models.CharField(max_length=100),
        ),
    ]
