# Generated by Django 5.0.4 on 2024-05-12 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_direccion_colonia_alter_direccion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.direccion'),
        ),
    ]
