# Generated by Django 5.0.4 on 2024-05-13 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apartado', models.DateField()),
                ('status', models.IntegerField()),
                ('fecha_limite', models.DateField()),
                ('temportal', models.BooleanField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='detallesApartado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apartado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartado.apartado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='apartado',
            name='productos',
            field=models.ManyToManyField(through='apartado.detallesApartado', to='productos.producto'),
        ),
    ]
